blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'contact/$', views.contact, name='contact'),
    url(r'^blog/$', views.blog_home, name='blog_home'),
    url(r'^blog/(?P<post_id>[0-9]+)/$', views.detail, name='detail')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Category(models.Model):
    title=models.CharField(max_length=100)
    def __str__(self):
        return self.title

class Post(models.Model):
    created_at=models.DateTimeField('date created')
    updated_at=models.DateTimeField('date updated')
    title=models.CharField(max_length=200)
    slug=models.SlugField(max_length=100)
    body=models.TextField(default="")
    category=models.ManyToManyField(Category)
    def __str__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from .models import Post

def blog_home(request):
    posts = Post.objects.order_by('-created_at')[:100]
    context = {'blogposts': posts}
    return render(request, 'blog/blog_home.html', context)

def index(request):
    return render(request, 'blog/index.html')

def contact(request):
    return render(request, 'blog/contact.html')


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/post.html', {'post': post})

blog/templates/blog/base.html
{% load static %}
{% csrf_token %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'blog:index' %}">hhonasoge</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ml-auto" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:blog_home' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="container" id="mainbody">
        {% block content %}
        {% endblock %}
        <!-- Footer -->
        <footer id="lab_social_icon_footer">
            <div class="text-center center-block">
                <a href="https://www.facebook.com/harsha.honasoge"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                <a href="https://github.com/hhonasoge"><i id="social-gh" class="fa fa-github-square fa-3x social"></i></a>
                <a href="https://www.linkedin.com/in/hhonasoge"><i id="social-ln" class="fa fa-linkedin-square fa-3x social"></i></a>
                <a href="mailto:harshadothonasogeatgmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
        </footer>
    </div>
  </body>
</html>

blog/templates/blog/blog_home.html
{% extends 'blog/base.html' %}

{% block content %}
{% if blogposts %}
{% for post in blogposts %}  
    <div class="blogpost">
        <h3><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h3>
    </div>
{% endfor %}
{% else %}
<p>No posts are available.</p>
{% endif %}
{% endblock %}

blog/templates/blog/blogposts.html
{% extends 'blog/base.html' %}

{% if blogposts %}
{% for post in blogposts %}
<div class="post">
    <h3><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h3>>
</div>
            <!-- <li><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></li> -->
{% endfor %}
{% else %}
<p>No posts are available.</p>
{% endif %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
<ul class="contact">
    <li class="contact-item">
      <a href="https://www.facebook.com/harsha.honasoge">Facebook</a>
    </li>
    <li class="contact-item">
        <a href="https://github.com/hhonasoge">Github</a>
    </li>
    <li class="contact-item">
        <a href="mailto:harshadothonasogeatgmail.com">Gmail</a>
    </li>
    <li class="contact-item">
        <a href="https://www.linkedin.com/in/hhonasoge">LinkedIn</a>
    </li>
  </ul>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="aboutme">
        <strong>I am Harsha</strong>
    </div>
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="blogpost">
<h1>{{ post.title }}</h1>
<h6>{{ post.updated_at }}</h6>
<h6>Topics:
{% if post.category %}
{% for category in post.category.all %}
    #{{category}}
{% endfor %}
{% endif %}
</h6>
<br><br>
<p> {{ post.body }}</p>
</div>

{% endblock %}